### ISSUE TITLE
Migration Exception: Undefined variable: settings

### ISSUE THREAD

**Issue by michaelroper** [craftcms/aws-s3#39]
Hey Andris!

I've been running with the `dev-craft-3.1` branch without issue for the last few weeks, but just FYI, the recent commit you made (e0636f1) is causing a migration error for me now..

After running a composer update and getting the latest commit..
```
  - Updating craftcms/cms (3.1.6.1 => 3.1.7): Loading from cache
  - Updating craftcms/server-check (1.1.6 => 1.1.7): Loading from cache
  - Updating league/flysystem-aws-s3-v3 (1.0.21 => 1.0.22): Loading from cache
  - Updating craftcms/aws-s3 dev-craft-3.1 (0c2b23b => 3cb4190):  Checking out 3cb4190265
```

I get this error running the migration...
```
Exception: Undefined variable: settings (/Users/michael.roper/Sites/website-v3/vendor/craftcms/aws-s3/src/migrations/m180929_165000_remove_storageclass_setting.php:30)
#0 /Users/michael.roper/Sites/website-v3/vendor/craftcms/aws-s3/src/migrations/m180929_165000_remove_storageclass_setting.php(30): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/Users/michael....', 30, Array)
#1 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/db/Migration.php(56): craft\awss3\migrations\m180929_165000_remove_storageclass_setting->safeUp()
#2 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\awss3\migrations\m180929_165000_remove_storageclass_setting))
#4 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#5 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
```
I'm using Environment variables for my secret settings, and have non-secret settings in `config/volumes.php`, if that makes a difference.

**Comment by andris-sevcenko** [comment]
I'll just call this one "friends don't let friends write migrations at 10pm" :)

**Comment by andris-sevcenko** [comment]
Closed via 4b6260d

**Comment by michaelroper** [comment]
Hah, good one! 😆 

How far away is this branch from a package release now?

**Comment by andris-sevcenko** [comment]
About 2 hours? Have to get to the office first :)

**Comment by michaelroper** [comment]
How's that for commitment! Love your work :)
