### ISSUE TITLE
Migration error: "Setting unknown property: craft\services\ProjectConfig::muteEvents"

### ISSUE THREAD

**Issue by OnBelayWebSolutions** [craftcms/aws-s3#44]
Hi.

Just installed craftcms/aws-s3 with composer on my local MAMP stack, when finish the installation i get a few migration errors, "Unknown Property: Setting unknown property: craft\services\ProjectConfig::muteEvents"

Looking at the migrations, it seems to be this line that's responsible:

```php
# m180929_165000_remove_storageclass_setting.php, line 23
$projectConfig->muteEvents = true;
```

Full error:

```
Unknown Property: Setting unknown property: craft\services\ProjectConfig::muteEvents

Migration: craft\awss3\migrations\m180929_165000_remove_storageclass_setting

Output:

Exception: Setting unknown property: craft\services\ProjectConfig::muteEvents (/Users/kristoffer/Documents/dev/craft3orango/vendor/yiisoft/yii2/base/Component.php:209)
#0 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/aws-s3/src/migrations/m180929_165000_remove_storageclass_setting.php(23): yii\base\Component->__set('muteEvents', true)
#1 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/db/Migration.php(56): craft\awss3\migrations\m180929_165000_remove_storageclass_setting->safeUp()
#2 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\awss3\migrations\m180929_165000_remove_storageclass_setting))
#4 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#5 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array)
#6 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#7 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#8 /Users/kristoffer/Documents/dev/craft3orango/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/kristoffer/Documents/dev/craft3orango/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#11 /Users/kristoffer/Documents/dev/craft3orango/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#12 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#13 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#14 /Users/kristoffer/Documents/dev/craft3orango/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#15 /Users/kristoffer/Documents/dev/craft3orango/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /Users/kristoffer/Documents/dev/craft3orango/web/index.php(21): yii\base\Application->run()
#17 {main}
```

Craft version: 3.1.0
AWS S3-version:  1.1.1

Am I missing something?

Thanks.

**Comment by andris-sevcenko** [comment]
Ah, my bad. AWS 1.1.1 requires Craft 3.1.2 or later. Going to update the requirements and push another release in a sec.

**Comment by andris-sevcenko** [comment]
Actually, 1.1.2 already requires Craft 3.1.5 or later, so you should just update the AWS plugin to at least 1.1.2.
