### ISSUE TITLE
Cannot install on Nitro

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/aws-s3#92]
### Description

```
ubuntu@nitro-dev:~/sites/funko-craftcms-nitro$ ./craft install/plugin aws-s3
*** installing aws-s3
Exception: Undefined index: location (/home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/aws-s3/src/migrations/Install.php:67)
#0 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/aws-s3/src/migrations/Install.php(67): yii\console\ErrorHandler->handleError()
#1 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/aws-s3/src/migrations/Install.php(33): craft\awss3\migrations\Install->_convertVolumes()
#2 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/db/Migration.php(52): craft\awss3\migrations\Install->safeUp()
#3 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\awss3\migrations\Install->up()
#4 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/base/Plugin.php(140): craft\db\MigrationManager->migrateUp()
#5 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/services/Plugins.php(521): craft\awss3\Plugin->install()
#6 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/console/controllers/InstallController.php(190): craft\services\Plugins->installPlugin()
#7 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\console\controllers\InstallController->actionPlugin()
#8 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#9 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#10 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/console/Controller.php(164): craft\console\controllers\InstallController->runAction()
#11 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/console/Controller.php(187): craft\console\controllers\InstallController->runAction()
#12 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Module.php(528): craft\console\controllers\InstallController->runAction()
#13 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/console/Application.php(180): craft\console\Application->runAction()
#14 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/console/Application.php(87): craft\console\Application->runAction()
#15 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#16 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Application.php(386): craft\console\Application->handleRequest()
#17 /home/ubuntu/sites/funko-craftcms-nitro/craft(22): craft\console\Application->run()
#18 {main}
*** installed aws-s3 successfully (time: 0.061s)
```

### Steps to reproduce

1. Set up a new site on Nitro.
2. Try to install this plugin.

### Additional info

- Craft version: 3.4.29.1
- PHP version: 7.4.x
- Database driver & version: MySQL 5.7

**Comment by andris-sevcenko** [comment]
The installation migration was not defensive enough. It had nothing to do with Nitro, however - just a regular oversight :)

Just cut the 1.2.9 release, so update away!
